---
# yaml-language-server: $schema=https://www.schemastore.org/pre-commit-config.json
default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: gofumpt
        name: format
        language: system
        entry: bash -lc 'go run mvdan.cc/gofumpt@v0.9.2 -w "$@"' --
        types: [go]

      - id: golangci-lint
        name: lint
        language: system
        entry: bash -lc 'go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.8.0 run --timeout=5m'
        pass_filenames: false

      - id: gotestsum
        name: tests
        language: system
        entry: bash -lc 'go run gotest.tools/gotestsum@v1.13.0 -- ./...'
        pass_filenames: false
